### ISSUE TITLE
Wikipedia page with slash in name confuses fetch, returns 404 page not found

### ISSUE THREAD

**Issue by RocketDerp** [codeledge/entitree-monorepo#24]
let article = getWikipediaArticle("Sex/Life", "en");

Fails for this page:

https://en.wikipedia.org/wiki/Sex/Life

P.S. There is a typo in the project README that it says 'let artice' variable name.

**Comment by mshd** [comment]
thanks for flagging this, will look into this soon.

**Comment by mshd** [comment]
The slash in an article name seems to work, I've added a test which passes.
https://github.com/codeledge/entitree-monorepo/pull/28
Please let me know if it works for you!

**Comment by RocketDerp** [comment]
Does the cited example "Sex/Life" work?
